version: '2'
services:
    web1:
        build: ./redisAgent
        ports:
            - "5000:5000"
        volumes:
            - .:/app
        depends_on:
            - redis
    redisagent1:
        image: redis
        ports:
            - "6379:6379"
    eureka:
        build: ./eureka
        image: eureka:latest
        ports:
            - "8080:8080"
