version: '2'
services:
    web:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/app
        depends_on:
            - redis
    redis:
        image: redis
    eureka:
        image: eureka:latest
        ports:
            - "8080:8080"
